<!DOCTYPE html>
<html>
<head>
    <title>${report.title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background-color: #f0f0f0; padding: 10px; margin-bottom: 20px; }
        .section { margin: 20px 0; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; }
        .footer { margin-top: 20px; font-size: 12px; color: #666; }
        .highlight { background-color: #fff3cd; }
        .error { color: red; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${report.title}</h1>
        <p>Generated on: ${.now?string("yyyy-MM-dd HH:mm:ss")}</p>
        <p>Report ID: ${report.id}</p>
    </div>

    <div class="section">
        <h2>Summary</h2>
        <p>Total Items: ${report.items?size}</p>
        <p>Status: 
            <#if report.status == "COMPLETED">
                <span style="color: green;">✓ Completed</span>
            <#elseif report.status == "PROCESSING">
                <span style="color: orange;">⟳ Processing</span>
            <#else>
                <span style="color: red;">✗ Failed</span>
            </#if>
        </p>
    </div>

    <div class="section">
        <h2>Items</h2>
        <#if report.items?? && report.items?size gt 0>
            <table>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Value</th>
                    <th>Status</th>
                </tr>
                <#list report.items as item>
                    <tr class="${item.highlight?then('highlight', '')}">
                        <td>${item.id}</td>
                        <td>${item.name!}</td>
                        <td>${item.value?string("0.00")}</td>
                        <td>
                            <#switch item.status>
                                <#case "ACTIVE">
                                    <span style="color: green;">Active</span>
                                    <#break>
                                <#case "PENDING">
                                    <span style="color: orange;">Pending</span>
                                    <#break>
                                <#default>
                                    <span style="color: red;">Inactive</span>
                            </#switch>
                        </td>
                    </tr>
                </#list>
            </table>
        <#else>
            <p class="error">No items found</p>
        </#if>
    </div>

    <div class="section">
        <h2>Statistics</h2>
        <#if report.statistics??>
            <ul>
                <li>Average Value: ${report.statistics.averageValue?string("0.00")}</li>
                <li>Total Value: ${report.statistics.totalValue?string("0.00")}</li>
                <li>Active Items: ${report.statistics.activeCount}</li>
            </ul>
        </#if>
    </div>

    <div class="footer">
        <p>Generated by FreeMarker Test</p>
        <#if report.metadata??>
            <p>Version: ${report.metadata.version!}</p>
            <p>Environment: ${report.metadata.environment!}</p>
        </#if>
    </div>
</body>
</html> 