<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; }
        .page-content {
            margin-bottom: 40px;
        }
        .footer {
            width: 100%;
            text-align: center;
            font-size: 12px;
            color: #888;
            position: running(footer);
            margin-top: 30px;
        }
        @page {
            @bottom-center {
                content: element(footer);
            }
        }
    </style>
</head>
<body>
    <#list reportDataList as reportData>
        <div class="page-content">
            <h1>Report Page ${reportData?index + 1}</h1>
            <p>${reportData.content}</p>
        </div>
        <div class="footer">
            Generated by SimplePdfGenerator — Page ${reportData?index + 1}
        </div>
        <#if reportData?has_next>
            <div style="page-break-after: always;"></div>
        </#if>
    </#list>
</body>
</html> 